<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'App__Entity__AvailableSpots__CLASSMETADATA__' => 0,
'App__Entity__PreRegistration__CLASSMETADATA__' => 1,

], [

0 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Id\\SequenceGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\SequenceGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\AvailableSpots',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\AvailableSpotsRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    2,
                ],
                'fieldMappings' => [
                    [
                        'id' => $o[1],
                        'basicKindergarten' => $o[2],
                        'basicPrimary' => $o[3],
                        'expandedKindergarten' => $o[4],
                        'expandedPrimary' => $o[5],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'basic_kindergarten' => 'basicKindergarten',
                        'basic_primary' => 'basicPrimary',
                        'expanded_kindergarten' => 'expandedKindergarten',
                        'expanded_primary' => 'expandedPrimary',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'basicKindergarten' => 'basic_kindergarten',
                        'basicPrimary' => 'basic_primary',
                        'expandedKindergarten' => 'expanded_kindergarten',
                        'expandedPrimary' => 'expanded_primary',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'available_spots',
                    ],
                ],
                'idGenerator' => [
                    $o[6],
                ],
                'sequenceGeneratorDefinition' => [
                    [
                        'sequenceName' => 'available_spots_id_seq',
                        'allocationSize' => '1',
                        'initialValue' => '1',
                    ],
                ],
                'name' => [
                    'App\\Entity\\AvailableSpots',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'integer',
                    'integer',
                    'integer',
                    'integer',
                ],
                'fieldName' => [
                    1 => 'id',
                    'basicKindergarten',
                    'basicPrimary',
                    'expandedKindergarten',
                    'expandedPrimary',
                ],
                'columnName' => [
                    1 => 'id',
                    'basic_kindergarten',
                    'basic_primary',
                    'expanded_kindergarten',
                    'expanded_primary',
                ],
            ],
        ],
        $o[0],
        [
            -6 => [
                'allocationSize' => 1,
                'sequenceName' => 'available_spots_id_seq',
            ],
        ]
    );
},
1 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Id\\SequenceGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\SequenceGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\PreRegistration',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\PreRegistrationRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    2,
                ],
                'fieldMappings' => [
                    [
                        'id' => $o[1],
                        'firstName' => $o[2],
                        'lastName' => $o[3],
                        'email' => $o[4],
                        'school' => $o[5],
                        'section' => $o[6],
                        'class' => $o[7],
                        'createdAt' => $o[8],
                        'week1' => $o[9],
                        'week2' => $o[10],
                        'week3' => $o[11],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'first_name' => 'firstName',
                        'last_name' => 'lastName',
                        'email' => 'email',
                        'school' => 'school',
                        'section' => 'section',
                        'class' => 'class',
                        'created_at' => 'createdAt',
                        'week1' => 'week1',
                        'week2' => 'week2',
                        'week3' => 'week3',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'firstName' => 'first_name',
                        'lastName' => 'last_name',
                        'email' => 'email',
                        'school' => 'school',
                        'section' => 'section',
                        'class' => 'class',
                        'createdAt' => 'created_at',
                        'week1' => 'week1',
                        'week2' => 'week2',
                        'week3' => 'week3',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'pre_registration',
                    ],
                ],
                'idGenerator' => [
                    $o[12],
                ],
                'sequenceGeneratorDefinition' => [
                    [
                        'sequenceName' => 'pre_registration_id_seq',
                        'allocationSize' => '1',
                        'initialValue' => '1',
                    ],
                ],
                'name' => [
                    'App\\Entity\\PreRegistration',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'string',
                    'string',
                    'string',
                    'string',
                    'string',
                    'string',
                    'datetime_immutable',
                    'boolean',
                    'boolean',
                    'boolean',
                ],
                'fieldName' => [
                    1 => 'id',
                    'firstName',
                    'lastName',
                    'email',
                    'school',
                    'section',
                    'class',
                    'createdAt',
                    'week1',
                    'week2',
                    'week3',
                ],
                'columnName' => [
                    1 => 'id',
                    'first_name',
                    'last_name',
                    'email',
                    'school',
                    'section',
                    'class',
                    'created_at',
                    'week1',
                    'week2',
                    'week3',
                ],
                'length' => [
                    2 => 255,
                    255,
                    255,
                    255,
                    255,
                    255,
                ],
            ],
        ],
        $o[0],
        [
            -12 => [
                'allocationSize' => 1,
                'sequenceName' => 'pre_registration_id_seq',
            ],
        ]
    );
},

]];
