<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8nUEyWj\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8nUEyWj/App_KernelProdContainer.php') {
    touch(__DIR__.'/Container8nUEyWj.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\Container8nUEyWj\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \Container8nUEyWj\App_KernelProdContainer([
    'container.build_hash' => '8nUEyWj',
    'container.build_id' => 'fc3a0de1',
    'container.build_time' => 1711226507,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container8nUEyWj');
