<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AvailableSpots extends \App\Entity\AvailableSpots implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'basicKindergarten' => [parent::class, 'basicKindergarten', null],
        "\0".parent::class."\0".'basicPrimary' => [parent::class, 'basicPrimary', null],
        "\0".parent::class."\0".'expandedKindergarten' => [parent::class, 'expandedKindergarten', null],
        "\0".parent::class."\0".'expandedPrimary' => [parent::class, 'expandedPrimary', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        'basicKindergarten' => [parent::class, 'basicKindergarten', null],
        'basicPrimary' => [parent::class, 'basicPrimary', null],
        'expandedKindergarten' => [parent::class, 'expandedKindergarten', null],
        'expandedPrimary' => [parent::class, 'expandedPrimary', null],
        'id' => [parent::class, 'id', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
