<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class PreRegistration extends \App\Entity\PreRegistration implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'class' => [parent::class, 'class', null],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null],
        "\0".parent::class."\0".'firstName' => [parent::class, 'firstName', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'lastName' => [parent::class, 'lastName', null],
        "\0".parent::class."\0".'school' => [parent::class, 'school', null],
        "\0".parent::class."\0".'section' => [parent::class, 'section', null],
        "\0".parent::class."\0".'week1' => [parent::class, 'week1', null],
        "\0".parent::class."\0".'week2' => [parent::class, 'week2', null],
        "\0".parent::class."\0".'week3' => [parent::class, 'week3', null],
        'class' => [parent::class, 'class', null],
        'createdAt' => [parent::class, 'createdAt', null],
        'email' => [parent::class, 'email', null],
        'firstName' => [parent::class, 'firstName', null],
        'id' => [parent::class, 'id', null],
        'lastName' => [parent::class, 'lastName', null],
        'school' => [parent::class, 'school', null],
        'section' => [parent::class, 'section', null],
        'week1' => [parent::class, 'week1', null],
        'week2' => [parent::class, 'week2', null],
        'week3' => [parent::class, 'week3', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
